name: RsAuto
main: Rs.Plugin.Auto.RsAutoMainClass
version: 1.3.3
api: 1.0.0
load: POSTWORLD
author: zmdd
description: Auto of Rs
depend:
 - RsFunction
commands:
 unregister:
  description: "注销某个玩家账号账号，消除密码"
  permission: Rs.Command.Auto.unregister
  usage: "/unregister [账号] #如果你是普通玩家，你就只能输入你自己的账号"
permissions:
 Rs.Command.Auto.unregister:
  default: true
  description: "注销某个玩家账号账号，消除密码"